DROP TABLE IF EXISTS users CASCADE;
-- CREATE USERS
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  first_name VARCHAR(255),
  last_name VARCHAR(255),
  city VARCHAR(255),
  country VARCHAR(255),
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255)
);